using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum JokeCategory
{
    General = 0,
    Simple = 1,
    Animals = 2,
    Science = 3,
    Games = 4,
    Differences = 5
}

public static class JokeDatabase
{
    static Dictionary<JokeCategory, string[]> database = new Dictionary<JokeCategory, string[]>() {
         {
            JokeCategory.Animals,
            new string[] {
                "Why did the cat start a tech company?",
                "What do you get when a penguin attends culinary school?",
                "Why did the octopus join a yoga class?",
                "How does an elephant cure its hiccups?",
                "What happened when the donkey started a landscaping business?",
                "Why do parrots get promoted in customer service jobs?",
                "What did the raccoon say when it entered a beauty pageant?",
                "Why did the lion start wearing glasses?",
                "What did the cheetah say after losing a race?",
                "How do cows stay entertained on long road trips?",
                "What's a giraffe's favorite party game?",
                "How does a squirrel remember where it buried its nuts?",
                "What do you call a bear who is always late to a party?",
                "How does a kangaroo stay calm at the dentist's office?",
                "What's an owl's favorite book genre?",
                "Why did the chameleon fail its job interview?",
                "What did the porcupine say to its crush?",
                "How does a dog plan a successful workout routine?",
                "What's a dolphin's secret talent?",
                "Why do ants make good detectives?",
                "What type of music does a snake prefer at a concert?",
                "Why do zebras make excellent fashion designers?",
                "How does a walrus stay cool during a heatwave?",
                "What did the bee say after winning a spelling bee?",
                "Why do rabbits make great comedians?",
                "Why did the beaver become a successful architect?",
                "How does a tortoise speed up its morning routine?",
                "What is a peacock's favorite dance move?",
                "Why did the alligator start a handbag business?",
                "What's the favorite sport of a group of seagulls?"
            }
        },
        {
            JokeCategory.Science,
            new string[] {
"Why did the atom refuse to bond with anyone at the party?",
"What's a physicist's favorite type of music?",
"How do astronomers organize their parties?",
"Why did the chemist's love life fizzle out?",
"What do you get when you cross a biologist with a stand-up comedian?",
"Why was the ampere feeling left out?",
"What did the Doppler effect say to the sound wave?",
"How does a scientist stay cool during a heat wave?",
"What do you call a mathematician who operates on themselves?",
"Why are robots terrible at picking up on social cues?",
"What would scientists use to catch a runaway electron?",
"Why did the microscope accuse the observatory of having a 'big ego'?",
"How do engineers dance at a party?",
"Why was the photon disappointed with its plane ticket?",
"What compliment did the cell pay to its biologist owner?",
"Why did the astronaut break up with their partner?",
"What do you get when you cross a geologist with an artist?",
"How do computer scientists unwind after a long day?",
"What do scientists have in common with bakers?",
"Why did the neuron feel so lonely?",
"How do you know if a paleontologist is bored at a party?",
"What do you call a bee that's an expert in chemistry?",
"What did the alien microbiologist say on its first visit to Earth?",
"What did the archeologist bring to the potluck dinner?",
"Why do climate scientists make bad gamblers?",
"What type of phone does an inventor use?",
"How did the genetics researcher flirt with their crush?",
"Why was the meteorologist late to the party?",
"What kind of drink does a quantum physicist order at the bar?",
"What would a chemist create by mixing love and logic?"
            }
        },
        {
            JokeCategory.Games,
            new string[] {
"Why did the chess pieces refuse to play on their day off?",
"What did the video game character say when asked about their love life?",
"How did the soccer ball get a promotion at work?",
"Why did the poker hand have to see a therapist?",
"What happened when the Tetris pieces attended a party?",
"Why did the Monopoly board join a dating app?",
"What did the Sudoku puzzle say to the crossword after a heated argument?",
"How did the Rubik's cube become an overnight social media sensation?",
"What did the bowling pins do after they found out they didn't make the cut for the Olympics?",
"Why did the jigsaw puzzle pieces start a band?",
"Why did the Scrabble tiles write a letter of complaint to their boss?",
"What do you call a group of video game characters at a reunion?",
"Why did the ping pong ball file for divorce from the paddle?",
"How did the deck of cards feel after completing a marathon?",
"What do video game controllers talk about when humans are away?",
"Why did the hide-and-seek champion retire at the top of their game?",
"Why did the dominoes decide to quit their day job?",
"How do board games enjoy their vacation time?",
"What do you call a computer game that's obsessed with cleaning?",
"How do video game consoles stay in shape?",
"What's a video game character's favorite type of sandwich?",
"Why did the video game developer go broke?",
"What's the difference between a video game and a bad hair day?",
"Why was the video game villain always late to work?",
"What do you get when you cross a classic arcade game with a farm animal?",
"How do video game characters stay cool during the summer?",
"Why did the video game character refuse to play cards?"
            }
        },
        {
            JokeCategory.Differences,
            new string[] {
"What's the difference between a magician and a politician?",
"What's the difference between a telemarketer and a vampire?",
"What's the difference between a snowstorm and a family reunion?",
"What's the difference between a stand-up comedian and a therapist?",
"What's the difference between a traffic jam and a dance floor?",
"What's the difference between a UFO and a software update?",
"What's the difference between a toddler and a houseplant?",
"What's the difference between a marathon and a shopping spree?",
"What's the difference between a ghost and a bad neighbor?",
"What's the difference between a roller coaster and a job interview?",
"What's the difference between an iceberg and a gossip session?",
"What's the difference between a meteor shower and a surprise party?",
"What's the difference between a catwalk and a treadmill?",
"What's the difference between a pizza delivery guy and a postman?",
"What's the difference between a yoga class and a wrestling match?",
"What's the difference between a library and a nightclub?",
"What's the difference between a selfie and a mugshot?",
"What's the difference between a rock concert and a symphony orchestra?",
"What's the difference between a day at the beach and a visit to the dentist?",
"What's the difference between a spaceship and a submarine?",
"What's the difference between a microwave and a time machine?",
"What's the difference between a bakery and a chemistry lab?",
"What's the difference between a gardener and a hairdresser?",
"What's the difference between a camping trip and a haunted house?",
"What's the difference between a fortune-teller and a meteorologist?",
"What's the difference between a detective and a stalker?",
"What's the difference between a puppet show and a political debate?",
"What's the difference between a roller rink and a hamster wheel?",
"What's the difference between a fashion show and a costume party?",
"What's the difference between a dog park and a dating app?",
"What's the difference between a rodeo and a boardroom meeting?",
"What's the difference between a video game and a day job?",
"What's the difference between a flight attendant and a traffic cop?",
"What's the difference between a zoo and a reality TV show?",
"What's the difference between a cruise ship and a haunted mansion?",
"What's the difference between a theme park and an exam hall?",
"What's the difference between a bank heist and a tax?",
"What's the difference between an artificial intelligence and a know-it-all?",
"What's the difference between a circus and a corporate office?",
"What's the difference between a coffee shop and a therapy session?",
"What's the difference between a treasure hunt and a scavenger hunt?",
"What's the difference between a workout session and a horror movie?",
"What's the difference between a gardener and a pirate?",
            }
        },
        {
            JokeCategory.Simple,
            new string[] {
"Why did the chicken cross the road?",
"How do you make a tissue dance?",
"Why don't scientists trust atoms?",
"What do you call fake spaghetti?",
"What kind of shoes do robbers wear?",
"Why did the tomato turn red?",
"How do you organize a space party?",
"What's the best way to catch a squirrel?",
"Why didn't the bicycle go to the party?",
"What do you get when you cross a snowman and a dog?",
"Why are frogs so happy?",
"What happens when you tell an egg a joke?"
            }
            },
        {
            JokeCategory.General,
            new string[] {
"Why did the houseplant break up with the gardener?",
"What do you call a dog that loves to take baths?",
"Why was the baker afraid of making a cake?",
"What do you get when you cross a dinosaur with a BBQ grill?",
"Why did the bicycle go to therapy",
"Why don't astronauts use calendars in space?",
"What did the sushi say to the bento box?",
"How does a tortoise text on a smartphone?",
"What do you call a bear who's always late to work?",
"What happened when the tomato turned red",
"Why are ghosts terrible at keeping secrets?",
"What do you call an alligator that knows the alphabet?",
"What do clouds use to keep their pants from falling down?",
"How does a scientist like their coffee in the morning?",
"What do computers snack on during a movie",
"Why did the scarecrow become a life coach?",
"What did the ocean say to the beach on their wedding day?",
"How does a pirate stay in shape?",
"Why was the lemon feeling bitter at the party?",
"What do cows use for their online dating profiles?",
"Why do soccer players make great bakers?",
"What kind of music does a tree listen to?",
"How do pasta chefs stay in shape?",
"What happened when the skeleton tried stand-up comedy?",
"What do you call a chameleon that can't change color?",
"Why do flamingos like yoga?",
"What happened at the math book's therapy session?",
"How does Santa Claus stay safe during COVID-19?",
"Why did the grapefruit go to prison?",
"What do you call a cat with a law degree?",
"Why did the banana go to school?",
"What do you call a snowman with a sunburn?",
"How do you get a baby astronaut to sleep?",
"What's the difference between a comet and a snowball?",
"Why do hamburgers make great detectives?",
"What do you call an owl that knows how to sew?",
"How do flowers get around town?",
"How does a robot take a shower?",
"Why was the strawberry so upset?",
"What kind of shoes do painters wear?",
"Why did the chicken join a band?",
"What do you call an argument between two electricians?",
"How do you make the perfect pancake mix?",
"What do pigeons use to edit their photos?",
"Why was the sand feeling down at the beach?",
"Why aren't snowmen good at sports?",
"Why do bees make terrible accountants?",
"What do you call a group of musical frogs?",
"How does the sun stay stylish?",
"What do you call a nervous macaroni noodle?",
"Why did the scarecrow start a podcast?",
"What do you call a dinosaur with an extensive shoe collection?",
"How does a computer scientist make their garden grow?",
"What did the frustrated bakery owner say after his tenth batch of burnt muffins?",
"How does an introverted cactus greet new friends?",
"Why did the bicycle apply for a job on the sales team?",
"When do astronauts eat lunch at work?",
"How does a fruit prevent sunburn while sitting on the beach?",
"What's the secret of a successful meatball marathon?",
"Why did the cookie go to art school?",
"How do two peas solve conflicts within their pod?",
"What happens when a piano gets caught in a thunderstorm?",
"Which is the most striking profession in Hollywood?",
"Who gives out free hugs in a library?",
"What did one sushi roll say to another during an argument?",
"How do baby puns mature as they grow older?",
"How does a mountain climber stay fashionable on expeditions?",
"What would be an owl's favorite genre of music?",
"Why did the snowman become an advice columnist?",
"What did the loaf of bread say to the toaster before breakfast?",
"What kind of jokes does bread-making yeast tell?",
"What's Einstein's favorite animal at the aquarium?",
"Why are bees notorious social media influencers? ",
"How do you keep ghosts from attending your birthday party? ",
"Why did the shovel decide to become a therapist?",
"How can you tell that chickens are great comedians? ",
"Which type of shoes would perfect for Santa Claus during summertime? ",
"At what time does a sandwich clock out for work?",
"Why was the refrigerator acting cold towards everyone?",
"Why do seagulls enjoy reading books about self-improvement?",
"How does a penguin perfect its figure-skating routine?",
"What happens when a pineapple auditions for a Broadway play?",
"Why did the potato start taking meditation classes?",
"How do you decide which peanut will win a beauty contest?",
"When does the moon feel most confident about its appearance?",
"Where do cats go to grab their morning coffee?",
"Why was the ice cube nervous before giving a speech?",
"How does the ocean stay fit and healthy?",
"What is the favorite flower of emotionally intelligent roses?",
"Why did the giraffe become a famous cellist? ",
"What's an alien's favorite dance move at parties?",
"Why do detectives make great chefs?",
"What happened to the piece of pizza who inherited millions of dollars?",
"Which sport are mummies living in Egypt passionate about?",
"How do tortoises prepare for long-distance marathons? ",
"In what key do birds sing their love songs?",
"What happens when superheroes exchange jokes instead of punches?",
"How did the avocado raise its self-esteem during quarantine?",
"Why was the lettuce embarrassed at the salad bar?",
"How did the sandwich win the marathon?",
"Why are bank vaults best at telling jokes?",
"What do you get when you mix dolphins with stand-up comedians?",
"How does a traffic light stay entertained during its downtime?",
"What's an astronaut's favorite type of humor?",
"What did the pizza say to its audience before telling its first joke?",
"How do you make an egg roll with just one word?",
"What's the funniest vegetable at Thanksgiving dinner?",
"How did the superhero stop an alien invasion with only a pun?",
"Where do snowman comedians perform their best jokes?",
"Why don't scientists use calendars for telling jokes?",
"How does a lobster feel when it's about to perform stand-up comedy? ",
"Which clothing item is always making jokes in your wardrobe?",
"What kind of comedy do video game characters prefer?",
"Why did the drill sergeant become a stand-up comedian?",
"Have you heard about sudoku's favorite type of joke? ",
"When should coffee lovers avoid watching stand-up routines? ",
"How does music cross paths with comedy in Antarctica? ",
"Where do ghosts go for the most hilarious haunted humor? ",
"How can you make people laugh using only binary code? ",
"How do farmers find humor in their daily life? ",
"Why was the baker always voted funniest during open mic nights? ",
"What makes a bathtub laugh during the nighttime? ",
"How do sharks crack jokes in the deep sea?",
"Why did the pencil move into the entertainment industry?",
"Who do you get when you cross a rapper with a stand-up comic?",
"Why was the eraser unhappy with its comedian friends?",
"What do you call a zebra that tells jokes at the zoo?",
"How does a tree cope with stage fright before telling woodland jokes?",
"Why did the pirate become a comedy club owner?",
"What's the most important ingredient for a magical comedy show?",
"How do bees entertain themselves while collecting nectar?",
"Why did Mount Everest decide to become a stand-up comedian?",
"What kind of joke does a UFO tell before abducting someone?",
"How does a factory alleviate boredom on the assembly line with humor?",
"Where do beach umbrellas go to listen to some great jokes?",
"Why did the clock start telling dad jokes during its lunch break?",
"How does a superhero use laughter as their secret weapon?",
"What happens when a car mechanic incorporates humor into his workday?",
"What's an iceberg's favorite comedy style in the Arctic Ocean? ",
"How do tables find amusement in their spare time? ",
"Why are robots becoming more popular in comedy clubs?",
"You ever notice how dogs at the park are like politicians?",
"Why did the vegan zombie only eat brain substitutes?",
"So, what's the deal with pineapple on pizza debates?",
"Have you heard about the new fitness trend, underwater basket weaving?",
"What did the astronaut use to get fresh ground coffee in space?",
"Why was the computer programmer always late for work?",
"How do introverts spice up their parties?",
"Why are cats terrible motivational speakers?",
"What happened when the paleontologist tried online dating?",
"How does a music producer organize their laundry?",
"How did the spy fail his cooking class?",
"You ever wonder why cows make terrible comedians?",
"What do aliens think of human reality TV shows?",
"Why was the bee always so good at math class?",
"How do sloths win marathons and races?",
"How do writers avoid distractions while working from home?",
"So, why are giraffes terrible secret agents?",
"Why do people keep comparing chess games to board meetings at work?",
"Why did the chicken start attending yoga classes?",
"How is going grocery shopping like trying to win a game show?",
"What's in common between earthworms and cold calls?",
"Did you hear about the snowman who got a job as a meteorologist?",
"Do you think squirrels secretly have office parties in the trees?"


            }
        }
        };



    static Dictionary<JokeCategory, HashSet<int>> alreadyPicked;

    public static void Reset()
    {
        alreadyPicked = new Dictionary<JokeCategory, HashSet<int>>();
        foreach (JokeCategory category in System.Enum.GetValues(typeof(JokeCategory)))
        {
            alreadyPicked[category] = new HashSet<int>();
        }
    }

    public static string GetJokeSetup(JokeCategory category = JokeCategory.General)
    {
        var jokes = database[category];
        for(; ; )
        {
            var candidateIndex = UnityEngine.Random.Range(0, jokes.Length);
            if(!alreadyPicked[category].Contains(candidateIndex))
            {
                alreadyPicked[category].Add(candidateIndex);
                return jokes[candidateIndex];
            }
        }
    }

}
